general.import = ["~/.config/alacritty/themes/themes/coolnight.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 15
padding.y = 15
startup_mode = "Maximized"

decorations = "buttonless"

[font]
normal.family = "MesloLGS NF"
size = 15

