general.import = ["~/.config/alacritty/themes/themes/coolnight.toml"]

[env]
TERM = "xterm-256color"

[terminal]
shell.program = "zellij"
shell.args = [
    "attach",
    "-c"
]

[window]
padding.x = 5
padding.y = 5
startup_mode = "Maximized"

decorations = "none"

[font]
normal.family = "MesloLGS NF"
normal.style = "Regular"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

