[settings]
experimental = true
verbose = false

[env]
DOTNET_CLI_TELEMETRY_OPTOUT = "1"
DOTNET_NOLOGO = "1"
DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "1"
DOTNET_ReadyToRun = "0"
DOTNET_TC_QuickJitForLoops = "1"
ASPNETCORE_ENVIRONMENT = "Development"
DOTNET_WATCH_RESTART_ON_RUDE_EDIT = "1"

[tasks."dotnet:build"]
description = "Builds the .NET solution. Warnings are NOT treated as errors."
quiet = true
dir = "{{ cwd }}"
run = '''
set -e

SOLUTION_FILE=$(mise run find-solution )

dotnet build "$SOLUTION_FILE" \
    /property:Configuration=Debug \
    /property:GenerateFullPaths=true \
    /consoleloggerparameters:NoSummary \
    /property:GenerateDocumentation=false \
    /property:IsLocalBuild=true
'''

[tasks."dotnet:build:fast"]
description = "Builds the .NET solution quickly just for development."
quiet = true
dir = "{{ cwd }}"
run = '''
set -e

SOLUTION_FILE=$(mise run find-solution )

dotnet build "$SOLUTION_FILE" \
    /property:Configuration=Debug \
    /property:IsLocalBuild=true \
    --nologo
'''

[tasks."dotnet:build:strict"]
description = "Builds the .NET solution from the scratch. Warnings are treated as errors."
quiet = true
dir = "{{ cwd }}"
run = '''
set -e

SOLUTION_FILE=$(mise run find-solution )

dotnet build "$SOLUTION_FILE" \
    /property:Configuration=Debug \
    /property:GenerateFullPaths=true \
    /consoleloggerparameters:NoSummary \
    /property:GenerateDocumentation=false \
    /property:IsLocalBuild=true \
    /property:TreatWarningsAsErrors=true \
    /warnaserror \
    --no-incremental
'''

[tasks."dotnet:coverage"]
depends = ["dotnet:build"]
description = "Runs tests and collects code coverage"
quiet = true
dir = "{{ cwd }}"
run = '''
set -e

SOLUTION_FILE=$(mise run find-solution)

dotnet test "$SOLUTION_FILE" \
    /property:GenerateFullPaths=true \
    /consoleloggerparameters:NoSummary \
    /property:CollectCoverage=true \
    /property:CoverletOutput=../CoverageResults/ \
    /property:MergeWith=../CoverageResults/coverage.json \
    /property:CoverletOutputFormat=\"lcov,json\" \
    -m:1
'''

[tasks."dotnet:test"]
depends = ["dotnet:build"]
description = "Runs the .NET unit tests (excludes integration tests)"
quiet = true
dir = "{{ cwd }}"
run = '''
set -e

SOLUTION_FILE=$(mise run find-solution)

dotnet test "$SOLUTION_FILE" --filter "FullyQualifiedName!~Integration"
'''

[tasks."dotnet:test:full"]
depends = ["dotnet:build"]
description = "Runs all .NET tests including integration tests"
quiet = true
dir = "{{ cwd }}"
run = '''
set -e

SOLUTION_FILE=$(mise run find-solution)

dotnet test "$SOLUTION_FILE"
'''

[tasks."dotnet:format"]
description = "Formats the .NET solution code using dotnet format"
quiet = true
dir = "{{ cwd }}"
run = '''
set -e

SOLUTION_FILE=$(mise run find-solution)

dotnet format "$SOLUTION_FILE"
'''
