# Claude Code — Provider Configuration
# Shortcuts for running Claude Code through custom Anthropic-compatible providers.
# Assumes provider API keys are already exported (e.g., from local_env).

_cco_openrouter_model() {
  local model="$1"
  local compact_window="$2"
  local extra_body="$3"
  shift 3

  if [[ -z "${OPENROUTER_API_KEY:-}" ]]; then
    print -u2 "OPENROUTER_API_KEY is not set"
    return 1
  fi

  local ANTHROPIC_BASE_URL="https://openrouter.ai/api"
  local ANTHROPIC_AUTH_TOKEN="$OPENROUTER_API_KEY"
  local ANTHROPIC_DEFAULT_OPUS_MODEL="$model"
  local ANTHROPIC_DEFAULT_SONNET_MODEL="$model"
  local ANTHROPIC_DEFAULT_HAIKU_MODEL="$model"
  local CLAUDE_CODE_SUBAGENT_MODEL="$model"
  local CLAUDE_CODE_AUTO_COMPACT_WINDOW="$compact_window"
  local CLAUDE_AUTOCOMPACT_PCT_OVERRIDE="90"
  local CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="1"
  local CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS="1"
  local -a claude_env=(
    "ANTHROPIC_BASE_URL=$ANTHROPIC_BASE_URL"
    "ANTHROPIC_AUTH_TOKEN=$ANTHROPIC_AUTH_TOKEN"
    "ANTHROPIC_API_KEY="
    "ANTHROPIC_DEFAULT_OPUS_MODEL=$ANTHROPIC_DEFAULT_OPUS_MODEL"
    "ANTHROPIC_DEFAULT_SONNET_MODEL=$ANTHROPIC_DEFAULT_SONNET_MODEL"
    "ANTHROPIC_DEFAULT_HAIKU_MODEL=$ANTHROPIC_DEFAULT_HAIKU_MODEL"
    "ANTHROPIC_MODEL=$ANTHROPIC_DEFAULT_OPUS_MODEL"
    "CLAUDE_CODE_SUBAGENT_MODEL=$CLAUDE_CODE_SUBAGENT_MODEL"
    "CLAUDE_CODE_AUTO_COMPACT_WINDOW=$CLAUDE_CODE_AUTO_COMPACT_WINDOW"
    "CLAUDE_AUTOCOMPACT_PCT_OVERRIDE=$CLAUDE_AUTOCOMPACT_PCT_OVERRIDE"
    "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=$CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC"
    "CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS=$CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS"
  )

  if [[ -n "$extra_body" ]]; then
    claude_env+=("CLAUDE_CODE_EXTRA_BODY=$extra_body")
  fi

  env "${claude_env[@]}" claude "$@"
}

ccoa() {
  if [[ -z "${OPENROUTER_API_KEY:-}" ]]; then
    print -u2 "OPENROUTER_API_KEY is not set"
    return 1
  fi

  local ANTHROPIC_BASE_URL="https://openrouter.ai/api"
  local ANTHROPIC_AUTH_TOKEN="$OPENROUTER_API_KEY"
  local ANTHROPIC_DEFAULT_FABLE_MODEL="anthropic/claude-fable-5[1m]"
  local ANTHROPIC_DEFAULT_OPUS_MODEL="anthropic/claude-opus-4.5[1m]"
  local ANTHROPIC_DEFAULT_SONNET_MODEL="anthropic/claude-sonnet-4.6[1m]"
  local ANTHROPIC_DEFAULT_HAIKU_MODEL="anthropic/claude-haiku-4.5"
  local ANTHROPIC_DEFAULT_FABLE_MODEL_NAME="Fable via OpenRouter"
  local ANTHROPIC_DEFAULT_OPUS_MODEL_NAME="Opus via OpenRouter"
  local ANTHROPIC_DEFAULT_SONNET_MODEL_NAME="Sonnet via OpenRouter"
  local ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME="Haiku via OpenRouter"
  local ANTHROPIC_DEFAULT_FABLE_MODEL_DESCRIPTION="Claude Fable 5 through Anthropic 1P"
  local ANTHROPIC_DEFAULT_OPUS_MODEL_DESCRIPTION="Claude Opus 4.5 through Anthropic 1P"
  local ANTHROPIC_DEFAULT_SONNET_MODEL_DESCRIPTION="Claude Sonnet 4.6 through Anthropic 1P"
  local ANTHROPIC_DEFAULT_HAIKU_MODEL_DESCRIPTION="Claude Haiku 4.5 through Anthropic 1P"
  local ANTHROPIC_MODEL="sonnet"
  local CLAUDE_CODE_SUBAGENT_MODEL="$ANTHROPIC_DEFAULT_SONNET_MODEL"
  local CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY="1"
  local CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="1"
  local CLAUDE_CODE_SKIP_FAST_MODE_ORG_CHECK="1"
  local CLAUDE_CODE_EXTRA_BODY='{"provider":{"order":["anthropic"],"allow_fallbacks":true}}'
  local -a claude_env=(
    "ANTHROPIC_BASE_URL=$ANTHROPIC_BASE_URL"
    "ANTHROPIC_AUTH_TOKEN=$ANTHROPIC_AUTH_TOKEN"
    "ANTHROPIC_API_KEY="
    "ANTHROPIC_DEFAULT_FABLE_MODEL=$ANTHROPIC_DEFAULT_FABLE_MODEL"
    "ANTHROPIC_DEFAULT_OPUS_MODEL=$ANTHROPIC_DEFAULT_OPUS_MODEL"
    "ANTHROPIC_DEFAULT_SONNET_MODEL=$ANTHROPIC_DEFAULT_SONNET_MODEL"
    "ANTHROPIC_DEFAULT_HAIKU_MODEL=$ANTHROPIC_DEFAULT_HAIKU_MODEL"
    "ANTHROPIC_DEFAULT_FABLE_MODEL_NAME=$ANTHROPIC_DEFAULT_FABLE_MODEL_NAME"
    "ANTHROPIC_DEFAULT_OPUS_MODEL_NAME=$ANTHROPIC_DEFAULT_OPUS_MODEL_NAME"
    "ANTHROPIC_DEFAULT_SONNET_MODEL_NAME=$ANTHROPIC_DEFAULT_SONNET_MODEL_NAME"
    "ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME=$ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME"
    "ANTHROPIC_DEFAULT_FABLE_MODEL_DESCRIPTION=$ANTHROPIC_DEFAULT_FABLE_MODEL_DESCRIPTION"
    "ANTHROPIC_DEFAULT_OPUS_MODEL_DESCRIPTION=$ANTHROPIC_DEFAULT_OPUS_MODEL_DESCRIPTION"
    "ANTHROPIC_DEFAULT_SONNET_MODEL_DESCRIPTION=$ANTHROPIC_DEFAULT_SONNET_MODEL_DESCRIPTION"
    "ANTHROPIC_DEFAULT_HAIKU_MODEL_DESCRIPTION=$ANTHROPIC_DEFAULT_HAIKU_MODEL_DESCRIPTION"
    "ANTHROPIC_MODEL=$ANTHROPIC_MODEL"
    "CLAUDE_CODE_SUBAGENT_MODEL=$CLAUDE_CODE_SUBAGENT_MODEL"
    "CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY=$CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY"
    "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=$CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC"
    "CLAUDE_CODE_SKIP_FAST_MODE_ORG_CHECK=$CLAUDE_CODE_SKIP_FAST_MODE_ORG_CHECK"
    "CLAUDE_CODE_EXTRA_BODY=$CLAUDE_CODE_EXTRA_BODY"
  )

  env "${claude_env[@]}" claude "$@"
}

ccoki() {
  _cco_openrouter_model \
    "moonshotai/kimi-k2.6[1m]" \
    "262144" \
    '{"provider":{"sort":"throughput","allow_fallbacks":true}}' \
    "$@"
}

ccods() {
  _cco_openrouter_model \
    "deepseek/deepseek-v4-pro[1m]" \
    "1048576" \
    '{"provider":{"sort":"price","allow_fallbacks":true}}' \
    "$@"
}

ccog() {
  _cco_openrouter_model \
    "z-ai/glm-5.2[1m]" \
    "1048576" \
    '{"provider":{"sort":"throughput","allow_fallbacks":true}}' \
    "$@"
}

ccks() {
  local ANTHROPIC_BASE_URL="https://api.kimi.com/coding/"
  local ANTHROPIC_AUTH_TOKEN="$KIMI_API_KEY"
  local ANTHROPIC_DEFAULT_OPUS_MODEL="kimi-for-coding"
  local ANTHROPIC_DEFAULT_SONNET_MODEL="kimi-for-coding"
  local ANTHROPIC_DEFAULT_HAIKU_MODEL="kimi-for-coding"
  local CLAUDE_CODE_SUBAGENT_MODEL="kimi-for-coding"
  local CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="1"
  local CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS="1"

  ANTHROPIC_BASE_URL="$ANTHROPIC_BASE_URL" \
  ANTHROPIC_AUTH_TOKEN="$ANTHROPIC_AUTH_TOKEN" \
  ANTHROPIC_DEFAULT_OPUS_MODEL="$ANTHROPIC_DEFAULT_OPUS_MODEL" \
  ANTHROPIC_DEFAULT_SONNET_MODEL="$ANTHROPIC_DEFAULT_SONNET_MODEL" \
  ANTHROPIC_DEFAULT_HAIKU_MODEL="$ANTHROPIC_DEFAULT_HAIKU_MODEL" \
  ANTHROPIC_MODEL="$ANTHROPIC_DEFAULT_OPUS_MODEL" \
  CLAUDE_CODE_SUBAGENT_MODEL="$CLAUDE_CODE_SUBAGENT_MODEL" \
  CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="$CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC" \
  CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS="$CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS" \
    claude "$@"
}
