# Claude Code — Baseten Provider Configuration
# Usage: ccb [claude-args...]

# Assumes BASETEN_API_KEY is already exported (e.g., from local_env)

ccbki() {
  local ANTHROPIC_BASE_URL="https://inference.baseten.co"
  local ANTHROPIC_AUTH_TOKEN="$BASETEN_API_KEY"
  local ANTHROPIC_DEFAULT_OPUS_MODEL="moonshotai/Kimi-K2.6"
  local ANTHROPIC_DEFAULT_SONNET_MODEL="moonshotai/Kimi-K2.6"
  local ANTHROPIC_DEFAULT_HAIKU_MODEL="moonshotai/Kimi-K2.6"
  local CLAUDE_CODE_SUBAGENT_MODEL="moonshotai/Kimi-K2.6"
  local CLAUDE_CODE_AUTO_COMPACT_WINDOW="262144"
  local CLAUDE_AUTOCOMPACT_PCT_OVERRIDE="90"
  local CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="1"
  local CLAUDE_CODE_EXTRA_BODY='{"thinking": {"type": "enabled", "keep": "all"}}'

  # Launch Claude Code with these vars scoped to this invocation only
  ANTHROPIC_BASE_URL="$ANTHROPIC_BASE_URL" \
  ANTHROPIC_AUTH_TOKEN="$ANTHROPIC_AUTH_TOKEN" \
  ANTHROPIC_DEFAULT_OPUS_MODEL="$ANTHROPIC_DEFAULT_OPUS_MODEL" \
  ANTHROPIC_DEFAULT_SONNET_MODEL="$ANTHROPIC_DEFAULT_SONNET_MODEL" \
  ANTHROPIC_DEFAULT_HAIKU_MODEL="$ANTHROPIC_DEFAULT_HAIKU_MODEL" \
  CLAUDE_CODE_SUBAGENT_MODEL="$CLAUDE_CODE_SUBAGENT_MODEL" \
  CLAUDE_CODE_AUTO_COMPACT_WINDOW="$CLAUDE_CODE_AUTO_COMPACT_WINDOW" \
  CLAUDE_AUTOCOMPACT_PCT_OVERRIDE="$CLAUDE_AUTOCOMPACT_PCT_OVERRIDE" \
  CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="$CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC" \
  CLAUDE_CODE_EXTRA_BODY="$CLAUDE_CODE_EXTRA_BODY" \
    claude "$@"
}

ccbg() {
  local ANTHROPIC_BASE_URL="https://inference.baseten.co"
  local ANTHROPIC_AUTH_TOKEN="$BASETEN_API_KEY"
  local ANTHROPIC_DEFAULT_OPUS_MODEL="zai-org/GLM-5.1"
  local ANTHROPIC_DEFAULT_SONNET_MODEL="zai-org/GLM-5.1"
  local ANTHROPIC_DEFAULT_HAIKU_MODEL="zai-org/GLM-5.1"
  local CLAUDE_CODE_SUBAGENT_MODEL="zai-org/GLM-5.1"
  local CLAUDE_CODE_AUTO_COMPACT_WINDOW="202800"
  local CLAUDE_AUTOCOMPACT_PCT_OVERRIDE="90"
  local CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="1"
  local CLAUDE_CODE_EXTRA_BODY='{"chat_template_args": {"enable_thinking": true}, "thinking": {"type": "enabled", "clear_thinking": false}}'

  ANTHROPIC_BASE_URL="$ANTHROPIC_BASE_URL" \
  ANTHROPIC_AUTH_TOKEN="$ANTHROPIC_AUTH_TOKEN" \
  ANTHROPIC_DEFAULT_OPUS_MODEL="$ANTHROPIC_DEFAULT_OPUS_MODEL" \
  ANTHROPIC_DEFAULT_SONNET_MODEL="$ANTHROPIC_DEFAULT_SONNET_MODEL" \
  ANTHROPIC_DEFAULT_HAIKU_MODEL="$ANTHROPIC_DEFAULT_HAIKU_MODEL" \
  CLAUDE_CODE_SUBAGENT_MODEL="$CLAUDE_CODE_SUBAGENT_MODEL" \
  CLAUDE_CODE_AUTO_COMPACT_WINDOW="$CLAUDE_CODE_AUTO_COMPACT_WINDOW" \
  CLAUDE_AUTOCOMPACT_PCT_OVERRIDE="$CLAUDE_AUTOCOMPACT_PCT_OVERRIDE" \
  CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="$CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC" \
  CLAUDE_CODE_EXTRA_BODY="$CLAUDE_CODE_EXTRA_BODY" \
    claude "$@"
}

ccks() {
  local ANTHROPIC_BASE_URL="https://api.kimi.com/coding/"
  local ANTHROPIC_AUTH_TOKEN="$KIMI_API_KEY"
  local ANTHROPIC_DEFAULT_OPUS_MODEL="kimi-for-coding"
  local ANTHROPIC_DEFAULT_SONNET_MODEL="kimi-for-coding"
  local ANTHROPIC_DEFAULT_HAIKU_MODEL="kimi-for-coding"
  local CLAUDE_CODE_SUBAGENT_MODEL="kimi-for-coding"
  local CLAUDE_CODE_AUTO_COMPACT_WINDOW="262144"
  local CLAUDE_AUTOCOMPACT_PCT_OVERRIDE="90"
  local CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="1"
  local CLAUDE_CODE_EXTRA_BODY='{"thinking": {"type": "enabled", "keep": "all"}}'

  ANTHROPIC_BASE_URL="$ANTHROPIC_BASE_URL" \
  ANTHROPIC_AUTH_TOKEN="$ANTHROPIC_AUTH_TOKEN" \
  ANTHROPIC_DEFAULT_OPUS_MODEL="$ANTHROPIC_DEFAULT_OPUS_MODEL" \
  ANTHROPIC_DEFAULT_SONNET_MODEL="$ANTHROPIC_DEFAULT_SONNET_MODEL" \
  ANTHROPIC_DEFAULT_HAIKU_MODEL="$ANTHROPIC_DEFAULT_HAIKU_MODEL" \
  CLAUDE_CODE_SUBAGENT_MODEL="$CLAUDE_CODE_SUBAGENT_MODEL" \
  CLAUDE_CODE_AUTO_COMPACT_WINDOW="$CLAUDE_CODE_AUTO_COMPACT_WINDOW" \
  CLAUDE_AUTOCOMPACT_PCT_OVERRIDE="$CLAUDE_AUTOCOMPACT_PCT_OVERRIDE" \
  CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="$CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC" \
  CLAUDE_CODE_EXTRA_BODY="$CLAUDE_CODE_EXTRA_BODY" \
    claude "$@"
}
